### ISSUE TITLE
Network dependency fetching.

### ISSUE THREAD

**Issue by pidgy** [n3d-b0y/PMKIDAttack#1]
Awesome job with this module, I found the interface super simple to use.

I forked this repository and made a few changes I thought might benefit some users.

The issue I, or other pineapple users might have is fetching the binaries from another users repository. I baked the required packages into the forked repository. I thought you may be interested in using this method as it adds simplicity to dependency gathering.

If you are interested I can make a pull request to your repository and add said changes.

Cheers.

**Comment by n3d-b0y** [comment]
Yes, pull request will be perfect
